modifed set up ssh job

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -94,14 +94,14 @@ jobs:
         run: |
           mkdir -p ~/.ssh
           chmod 700 ~/.ssh
-          cp scripts/private_key.pem ~/.ssh/id_rsa
+          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
           touch ~/.ssh/known_hosts
 
           # Add all EC2 servers to known_hosts dynamically
           while read -r server; do
             echo "Adding $server to known_hosts"
-            ssh-keyscan -H "$server" >> ~/.ssh/known_hosts
+            ssh-keyscan -H "$server" >> ~/.ssh/known_hosts || echo "Failed to add $server"
           done < scripts/serverlist.txt
         shell: bash
 
